- name: Create Xen Orchestra directory
  become: true
  ansible.builtin.file:
    path: "{{ xen_orchestra_dir }}"
    state: directory
    owner: "{{ xen_orchestra_svc_user }}"
    group: "{{ xen_orchestra_svc_group }}"
    mode: "770"

- name: Clone Xen Orchestra repo to temp destination
  become: true
  become_user: "{{ xen_orchestra_svc_user }}"
  ansible.builtin.git:
    repo: "{{ xen_orchestra_repo }}"
    dest: "{{ xen_orchestra_tmp_dir }}"
    version: "{{ xen_orchestra_version }}"

- name: Copy cloned Xen Orchestra repo to main directory
  become: true
  become_user: "{{ xen_orchestra_svc_user }}"
  ansible.builtin.copy:
    src: "{{ xen_orchestra_tmp_dir }}/"
    dest: "{{ xen_orchestra_dir }}"
    remote_src: true
    owner: "{{ xen_orchestra_svc_user }}"
    group: "{{ xen_orchestra_svc_group }}"
    
- name: Remove temp git clone destination
  become: true
  ansible.builtin.file:
    path: "{{ xen_orchestra_tmp_dir }}"
    state: absent

- name: Build project
  become: true
  become_user: "{{ xen_orchestra_svc_user }}"
  ansible.builtin.command: "{{ item }}"
  args:
    chdir: "{{ xen_orchestra_dir }}"
  register: output
  changed_when: output.rc == 0
  failed_when: output.rc != 0
  loop:
    - yarn
    - yarn build

- name: Include config tasks
  ansible.builtin.include_tasks: config.yml

- name: Start xo-server
  become: true
  become_user: "{{ xen_orchestra_svc_user }}"
  ansible.builtin.command: yarn start
  args:
    chdir: "{{ xen_orchestra_dir }}/packages/xo-server"
  register: output
  changed_when: output.rc == 0
  failed_when: output.rc != 0
