- name: Create Xen Orchestra dir
  become: true
  ansible.builtin.file:
    path: "{{ xen_orchestra_dir }}"
    state: directory
    owner: "{{ xen_orchestra_svc_user }}"
    group: "{{ xen_orchestra_svc_group }}"
    mode: "770"

- name: Clone Xen Orchestra repo
  become: true
  become_user: "{{ xen_orchestra_svc_user }}"
  ansible.builtin.git:
    repo: "{{ xen_orchestra_repo }}"
    dest: "{{ xen_orchestra_dir }}"
    version: "{{ xen_orchestra_version }}"
    force: true

- name: Build project
  become: true
  become_user: "{{ xen_orchestra_svc_user }}"
  ansible.builtin.command: "{{ item }}"
  args:
    chdir: "{{ xen_orchestra_tmp_dir }}"
  register: output
  changed_when: output.rc == 0
  failed_when: output.rc != 0
  loop:
    - yarn
    - yarn build

- name: Include config tasks
  ansible.builtin.include_tasks: config.yml

- name: Start xo-server
  become: true
  become_user: "{{ xen_orchestra_svc_user }}"
  ansible.builtin.command: yarn start
  args:
    chdir: "{{ xen_orchestra_dir }}"
  register: output
  changed_when: output.rc == 0
  failed_when: output.rc != 0
