- name: Include prerequisite tasks
  ansible.builtin.include_tasks: prereqs.yml

- name: Include user and group creation tasks
  ansible.builtin.include_tasks: user.yml
  when: 
   - "xen_orchestra_svc_user != 'root'"
   - "xen_orchestra_svc_group != 'root'"

- name: Include build tasks
  ansible.builtin.include_tasks: build.yml

- name: Include service tasks
  ansible.builtin.include_tasks: service.yml
