- name: Install yarn with npm
  become: true
  community.general.npm:
    name: yarn

- name: Install prerequisite packages
  become: true
  ansible.builtin.apt:
    name: "{{ xo_prereqs }}"

- name: Ensure redis is running
  become: true
  ansible.builtin.service:
    name: redis.service
    state: started
