- name: Set Xen Orchestra user homedir for non-global install
  ansible.builtin.set_fact:
    xen_orchestra_home: /home/xo
  when: "'xen_orchestra_global' != true"

- name: Set Xen Orchestra user homedir for global install
  ansible.builtin.set_fact:
    xen_orchestra_home: "{{ xen_orchestra_dir }}"
  when: "'xen_orchestra_global' == true"

- name: Create Xen Orchestra group
  become: true
  ansible.builtin.group:
    name: "{{ xen_orchestra_svc_group }}"
    state: present

- name: Create Xen Orchestra user
  become: true
  ansible.builtin.user:
    name: "{{ xen_orchestra_svc_user }}"
    group: "{{ xen_orchestra_svc_group }}"
    shell: /bin/bash
    home: "{{ xen_orchestra_dir }}"
    skeleton: false
    state: present

- name: Give required sudo permissions to Xen Orchestra user
  become: true
  community.general.sudoers:
    name: xen-orchestra
    user: "{{ xen_orchestra_svc_user }}"
    runas: root
    nopassword: true
    commands:
      - /bin/mount
      - /bin/umount
      - /bin/findmnt
    state: present
